# Generated by Django 4.0.7 on 2024-11-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('W', 'Web'), ('S', 'Security')], default='W', max_length=1),
            preserve_default=False,
        ),
    ]
