# Generated by Django 4.0.7 on 2024-11-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('W', 'Web development'), ('S', 'security')], max_length=1),
        ),
    ]
